### ISSUE TITLE
This looks exactly what I was looking for! I have some questions

### ISSUE THREAD

**Issue by venturaEffect** [dan-online/bunnycdn-stream#64]
First of all congrats on your work!

I have some questions.
1. Is it up to date?
2. Does it create and update all at once?
3. Can I pass more parameters thann just the title and collectionId? I want to pass genres, duration,... It is important to pass those parameters.
4. Is it possible to call the videos based on one parameter passed on the data? Let's say, genre=horror.

Again, thanks a lot! This project is awesome!

**Comment by dan-online** [comment]
Hey @venturaEffect 

Sure I can answer your questions:

1. Coincidentally I'm revisiting this project to update it for the Bunny APIs, possibly a v2 or v1.1 which should fix any issues
2. With [``createAndUploadVideo``](https://github.com/dan-online/bunnycdn-stream/blob/main/docs/classes/BunnyCdnStream.md#createanduploadvideo) you can do both operations
3. While updating I will make sure all functions can pass all data options, so that should be possible
4. At the moment while this is not possible, I'll check the API docs to see if theres a search or similar get request that could help

**Comment by venturaEffect** [comment]
Thanks Dan!

Let me know if you are available to talk deeper about it.

Really like what you are doing and maybe I'm in need of an expert on this field.

Appreciate!

**Comment by dan-online** [comment]
Just some info, you could perhaps use the ``metaTags`` to add genre, or perhaps collections to sort your videos and then you can list by specific collection.

If you want to talk more here's my discord: DanCodes#4445

**Comment by venturaEffect** [comment]
Nice!

Sent you a request on Discord!
